# Testing Transform functions

In [4]:
import numpy as np

In [10]:
square = np.array([
    [-1, 1, 1, -1, -1],
    [-1, -1, 1, 1, -1],
])
square = np.append(square, np.ones((1,square.shape[1])),0)
print(square)

[[-1.  1.  1. -1. -1.]
 [-1. -1.  1.  1. -1.]
 [ 1.  1.  1.  1.  1.]]


In [5]:
import transform as tf

T = tf.trans(1,1).dot(tf.rot(np.pi/4)).dot(tf.trans(0,2))
new_square = np.matmul(T, square)

print(T)

[[ 0.70710678 -0.70710678 -0.41421356]
 [ 0.70710678  0.70710678  2.41421356]
 [ 0.          0.          1.        ]]


In [ ]:
import matplotlib.pyplot as plt 

plt.figure()

plt.plot(square[0,:], square[1,:], new_square[0,:], new_square[1,:])

plt.grid(True)
plt.gca().set_aspect('equal', adjustable='box')
plt.show()


In [ ]:
import matplotlib.pyplot as plt 
fig = plt.figure()
ax = plt.axes(projection='3d')



cube = np.array([
    [-1, 1, 1, -1, -1, -1, 1, 1, -1, -1],
    [-1, -1, 1, 1, -1, -1, -1, 1, 1, -1],
    [0, 0, 0, 0, 0, 2, 2, 2, 2, 2]
])

ax.plot3D(cube[0,:], cube[1,:], cube[2,:])

In [ ]:
s = 'hello everyone this is a string'

l = s.split(' ')
l

In [ ]:
word = 'hello'
print(word[1:])

In [ ]:
a = np.array([
    [1,2,3,4,5,11],
    [6,7,8,9,10,12],
    [1,1,1,2,2,2],
])


In [16]:
import numpy as np
print(np.sqrt(4))

2.0


In [2]:
l = [1,2,3,4,5]
print(l.index(3))

2


In [15]:
a = np.array([
    [1,2,0.2,4],
    [0.5,6,7,8],
])
b = np.array([
    [10,10,10,10],
    [20,20,20,20],
])
print(a+b)

[[11.  12.  10.2 14. ]
 [20.5 26.  27.  28. ]]


In [2]:
print(np.pi)

3.14159265359


In [11]:
a = [0,1,2,3]
print(a[0:2])

[0, 1]


In [3]:
a = np.linspace(2,100,10)
a

array([  2.        ,  12.88888889,  23.77777778,  34.66666667,
        45.55555556,  56.44444444,  67.33333333,  78.22222222,
        89.11111111, 100.        ])

In [22]:
a = [[np.array([1,2,3]), np.array([4,5,6]), np.array([1,2,3])], [np.array([1,2,3]), np.array([4,5,6]), np.array([1,2,3])]]

b = []
c = []

for l in a:
    for item in l:
        c.append(np.copy(item))
    b.append(c)
    c = []

b[1][2][1]=300
print(a)
print(b)

[[array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3])], [array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3])]]
[[array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3])], [array([1, 2, 3]), array([4, 5, 6]), array([  1, 300,   3])]]


In [15]:
a = []
for i in range(10):
    a.append(i)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
