In [4]:
import numpy as np

In [10]:
a = np.array([
    [2, 2, 2],
    [1, 1, 1],
    [3, 3, 3],
])
print(a)

[[2 2 2]
 [1 1 1]
 [3 3 3]]


In [11]:
a[np.lexsort((a[:,2], ))]

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [12]:
print(a)

[[2 2 1]
 [2 1 2]
 [3 3 3]]
